export const AIRPORTS = [
    { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "USA" },
    { code: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China" },
    { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
    { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "USA" },
    { code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan" },
    { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
    { code: "LHR", name: "Heathrow Airport", city: "London", country: "UK" },
    { code: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China" },
    { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
    { code: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "USA" },
    { code: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands" },
    { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
    { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
    { code: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China" },
    { code: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "USA" },
    { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore" },
    { code: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
    { code: "DEN", name: "Denver International Airport", city: "Denver", country: "USA" },
    { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
    { code: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "USA" },
    { code: "BCN", name: "Josep Tarradellas Barcelona-El Prat Airport", city: "Barcelona", country: "Spain" },
    { code: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid", country: "Spain" },
    { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
    { code: "FCO", name: "Leonardo da Vinci-Fiumicino Airport", city: "Rome", country: "Italy" },
    { code: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada" },
    { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
    { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
    { code: "GRU", name: "São Paulo/Guarulhos–Governador André Franco Montoro International Airport", city: "São Paulo", country: "Brazil" },
    { code: "MEX", name: "Mexico City International Airport", city: "Mexico City", country: "Mexico" },
    { code: "MIA", name: "Miami International Airport", city: "Miami", country: "USA" },
    { code: "LAS", name: "Harry Reid International Airport", city: "Las Vegas", country: "USA" },
    { code: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", country: "USA" },
    { code: "EWR", name: "Newark Liberty International Airport", city: "Newark", country: "USA" },
    { code: "MCO", name: "Orlando International Airport", city: "Orlando", country: "USA" },
    { code: "CLT", name: "Charlotte Douglas International Airport", city: "Charlotte", country: "USA" },
    { code: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix", country: "USA" },
    { code: "IAH", name: "George Bush Intercontinental Airport", city: "Houston", country: "USA" },
    { code: "BOS", name: "Logan International Airport", city: "Boston", country: "USA" },
    { code: "MSP", name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis", country: "USA" },
    { code: "DTW", name: "Detroit Metropolitan Wayne County Airport", city: "Detroit", country: "USA" },
    { code: "FLL", name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale", country: "USA" },
    { code: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", country: "USA" },
    { code: "LGA", name: "LaGuardia Airport", city: "New York", country: "USA" },
    { code: "BWI", name: "Baltimore/Washington International Thurgood Marshall Airport", city: "Baltimore", country: "USA" },
    { code: "SLC", name: "Salt Lake City International Airport", city: "Salt Lake City", country: "USA" },
    { code: "SAN", name: "San Diego International Airport", city: "San Diego", country: "USA" },
    { code: "IAD", name: "Washington Dulles International Airport", city: "Washington D.C.", country: "USA" },
    { code: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington D.C.", country: "USA" },
    { code: "TPA", name: "Tampa International Airport", city: "Tampa", country: "USA" },
    { code: "PDX", name: "Portland International Airport", city: "Portland", country: "USA" },
    { code: "HNL", name: "Daniel K. Inouye International Airport", city: "Honolulu", country: "USA" },
    { code: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "Canada" },
    { code: "YUL", name: "Montréal-Pierre Elliott Trudeau International Airport", city: "Montreal", country: "Canada" },
    { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
    { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
    { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
    { code: "OSL", name: "Oslo Airport", city: "Oslo", country: "Norway" },
    { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
    { code: "HEL", name: "Helsinki Airport", city: "Helsinki", country: "Finland" },
    { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
    { code: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
    { code: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece" },
    { code: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy" },
    { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
    { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
    { code: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
    { code: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "Hungary" },
    { code: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania" },
    { code: "SAW", name: "Sabiha Gökçen International Airport", city: "Istanbul", country: "Turkey" },
    { code: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia" },
    { code: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia" },
    { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
    { code: "AUH", name: "Zayed International Airport", city: "Abu Dhabi", country: "UAE" },
    { code: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "Israel" },
    { code: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
    { code: "JNB", name: "O. R. Tambo International Airport", city: "Johannesburg", country: "South Africa" },
    { code: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "South Africa" },
    { code: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria" },
    { code: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya" },
    { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India" },
    { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", country: "India" },
    { code: "BLR", name: "Kempegowda International Airport", city: "Bangalore", country: "India" },
    { code: "MAA", name: "Chennai International Airport", city: "Chennai", country: "India" },
    { code: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata", country: "India" },
    { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", country: "India" },
    { code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia" },
    { code: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "Indonesia" },
    { code: "DPS", name: "I Gusti Ngurah Rai International Airport", city: "Denpasar", country: "Indonesia" },
    { code: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines" },
    { code: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam" },
    { code: "HAN", name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam" },
    { code: "TPE", name: "Taoyuan International Airport", city: "Taipei", country: "Taiwan" },
    { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "China" },
    { code: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan" },
    { code: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
    { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
    { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
    { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
    { code: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia" },
    { code: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "Argentina" },
    { code: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "Chile" },
    { code: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "Colombia" },
    { code: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "Peru" },
    { code: "PTY", name: "Tocumen International Airport", city: "Panama City", country: "Panama" },
];
